baseURL = "/"
languageCode = "en-us"
title = "Exegetic Training"
buildFuture = true
staticDir = ["static"]


[params]
        navImage = "img/exegetic-banner-white.svg" 
        headerImage = "img/training.png"
        